version: '3.8'

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: stone_sod_crm
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    restart: always
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgres://user:password@db:5432/stone_sod_crm
    depends_on:
      - db
    volumes:
      - ./api:/app
      - api_node_modules:/app/node_modules

  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile.nextjs
    restart: always
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://api:3001
    depends_on:
      - api
    volumes:
      - .:/app
      - nextjs_node_modules:/app/node_modules

volumes:
  db_data:
  api_node_modules:
  nextjs_node_modules: