version: '3.8'

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: stone_sod_crm
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d stone_sod_crm"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    restart: always
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgres://user:password@db:5432/stone_sod_crm
      NEXT_PUBLIC_URL: http://nextjs:3000
    depends_on:
      db:
        condition: service_started
    

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.nextjs
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      api:
        condition: service_started
    

volumes:
  db_data: