services:
  app:
    build: 
      context: ./app
    ports:
      - "3000:3000"
    env_file: ./.env
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./app:/app
      - /app/node_modules
    command: bash -c "PATH=/app/node_modules/.bin:$PATH npm run dev"